//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevOpsNinjaUI.RESX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevOpsNinjaUI.RESX.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&apos;1.0&apos; output-format=&apos;xml-platform&apos; mapping=&apos;logical&apos;&gt;
        ///&lt;entity name=&quot;solution&quot;&gt;
        ///&lt;attribute name = &quot;uniquename&quot;/&gt;
        ///&lt;attribute name = &quot;friendlyname&quot;/&gt;
        ///&lt;attribute name = &quot;isapimanaged&quot;/&gt;
        ///&lt;attribute name = &quot;uniquename&quot;/&gt;&lt;attribute name = &quot;ismanaged&quot;/&gt;
        ///&lt;attribute name = &quot;ismanagedname&quot;/&gt;&lt;attribute name = &quot;publisherid&quot; /&gt;
        ///&lt;attribute name = &quot;publisheridname&quot;/&gt;&lt;attribute name = &quot;solutionpackageversion&quot; /&gt;
        ///&lt;attribute name = &quot;version&quot; /&gt;
        ///&lt;filter type = &quot;and&quot; &gt;&lt;condition attribute = &quot;ismanaged&quot; o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FetchLoadUnmanagedSolutions {
            get {
                return ResourceManager.GetString("FetchLoadUnmanagedSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;importexportxml start=&quot;637863471582752120&quot; stop=&quot;637863471662440591&quot; progress=&quot;1.23674911660777&quot; processed=&quot;true&quot; errorcode=&quot;-2147188685&quot; succeeded=&quot;failure&quot; status=&quot;Solution manifest import: FAILURE: The following solution cannot be imported: MCSHHS_STAAND_Workflows. Some dependencies are missing. The missing dependencies are : &amp;lt;MissingDependencies&amp;gt;&amp;lt;MissingDependency&amp;gt;&amp;lt;Required type=&amp;quot;1&amp;quot; schemaName=&amp;quot;mcshhs_brbappointmentconfig&amp;quot; displayName=&amp;quot;BRB Appointment Config&amp;quot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResult {
            get {
                return ResourceManager.GetString("TestResult", resourceCulture);
            }
        }
    }
}
