//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevOpsNinjaUI.RESX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevOpsNinjaUI.RESX.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&apos;1.0&apos; output-format=&apos;xml-platform&apos; mapping=&apos;logical&apos;&gt;
        ///&lt;entity name=&quot;solution&quot;&gt;
        ///&lt;attribute name = &quot;uniquename&quot;/&gt;
        ///&lt;attribute name = &quot;friendlyname&quot;/&gt;
        ///&lt;attribute name = &quot;isapimanaged&quot;/&gt;
        ///&lt;attribute name = &quot;uniquename&quot;/&gt;&lt;attribute name = &quot;ismanaged&quot;/&gt;
        ///&lt;attribute name = &quot;ismanagedname&quot;/&gt;&lt;attribute name = &quot;publisherid&quot; /&gt;
        ///&lt;attribute name = &quot;publisheridname&quot;/&gt;&lt;attribute name = &quot;solutionpackageversion&quot; /&gt;
        ///&lt;attribute name = &quot;version&quot; /&gt;
        ///&lt;filter type = &quot;and&quot; &gt;&lt;condition attribute = &quot;ismanaged&quot; o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FetchLoadUnmanagedSolutions {
            get {
                return ResourceManager.GetString("FetchLoadUnmanagedSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;resultset morerecords=&quot;0&quot; paging-cookie=&quot;&amp;lt;cookie page=&amp;quot;1&amp;quot;&amp;gt;&amp;lt;createdon last=&amp;quot;2021-09-20T16:09:31-00:00&amp;quot; first=&amp;quot;2022-03-23T16:54:58-00:00&amp;quot; /&amp;gt;&amp;lt;solutionid last=&amp;quot;{25A01723-9F63-4449-A3E0-046CC23A2902}&amp;quot; first=&amp;quot;{7D8620F2-C9AA-EC11-B3FE-001DD8030A8D}&amp;quot; /&amp;gt;&amp;lt;/cookie&amp;gt;&quot;&gt;
        ///	&lt;result&gt;
        ///		&lt;friendlyname&gt;SHASHANK TEST&lt;/friendlyname&gt;
        ///		&lt;isapimanaged&gt;0&lt;/isapimanaged&gt;
        ///		&lt;uniquename&gt;SHASHANKTEST&lt;/uniquename&gt;
        ///		&lt;ismanaged name=&quot;Unmanaged&quot;&gt;0&lt;/ismanaged&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResult {
            get {
                return ResourceManager.GetString("TestResult", resourceCulture);
            }
        }
    }
}
